apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
        - name: myapp
          image: myapp:latest          # Use your locally built image
          imagePullPolicy: Never       # Prevent pulling from Docker Hub
          ports:
            - containerPort: 3000
          env:
            - name: MONGO_URI
              value: "mongodb://mongouser:password@mongodb:27017/"
